### ISSUE TITLE
Issue in connecting with --tls 1.2

### ISSUE THREAD

**Issue by ayushbindlish** [tempesta-tech/tls-perf#9]
**Steps to reproduce:**

```
openssl version
OpenSSL 1.1.1j  16 Feb 2021
```

```openssl s_server -accept :4433 -cert cert2048.pem  -key key2048.pem  -debug -msg```

```
./tls-perf -n 10 --tls 1.2 127.0.0.1 4433
Running TLS benchmark with following settings:
Host:        127.0.0.1 : 4433
TLS version: 1.2
Cipher:      ECDHE-ECDSA-AES128-GCM-SHA256
TLS tickets: off
Duration:    0

( All peers are active, start to gather statistics )
ERROR: cannot establish even one TLS connection: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

**Comment by krizhanovsky** [comment]
Hi @ayushbindlish ,

thank you for the bug report! The commit https://github.com/tempesta-tech/tls-perf/commit/11392a1da6f7cf715a624ebcb0efcb4b47af1e43 should fix the problem.

By default the tool uses ECDHE-ECDSA-AES128-GCM-SHA256 cipher suite (see the `Cipher` field in the banner) for TLS 1.2. Since there is `2048` in the names of you key and certificate, I assume you use RSA, so `tls-perf` can not establish a handshake (you might noticed `tls_post_process_client_hello:no shared cipher` error in the `s_server` output).

The mentioned comment uses any available ciphersuite by default.

Could you please check whether the problem is gone?

**Comment by ayushbindlish** [comment]
Thanks for the quick fix. I have verified the fix and it is working fine. 
Also, can we use this with https? Like apache bench or it will only support tcp?

**Comment by ayushbindlish** [comment]
And what cipher suite naming convention is being used? NIST or OpenSSL?
ref: https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

**Comment by ikoveshnikov** [comment]
>  Also, can we use this with https? Like apache bench or it will only support tcp?

No. The tool is designed to stress only TLS handshake processing to analyze implementation effectiveness.  There are variety of tools that work with https, like `ab` or `wrk`. They also may stress TLS handshakes if not configured for keeping connections alive. But they doesn't allow to stress _only_ TLS layer nor to configure SSL options like ciphers directly. 

The `tls_perf` is exactly opposite - it doesn't send any application data inside of established connections, and allows to configure some handshake parameters directly. Very handy for TLS development.

**Comment by ayushbindlish** [comment]
Thank you @ikoveshnikov for explaining that in detail.
